name: Build & Deploy site using GH Pages.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install dependencies
        run: npm ci
      - name: Build Artifacts
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v1
